### ISSUE TITLE
Disable shadow root

### ISSUE THREAD

**Issue by d0whc3r** [Silind/create-react-web-component#2]
How can I disable shadow root for the generated web component?

**Comment by SimonHoiberg** [comment]
Hi @d0whc3r 

There was no current support for disabling the shadow root, but I actually think it's a very good suggestion.

So I made a patch release this morning including this feature :+1: 

In order to disable the shadow root, you should do the following:

- Update your version of _create-react-web-component_ to **2.0.13** in _package.json_:
`"create-react-web-component": "2.0.13"`
  
- Now you can disable the shadow root in _src/index.js_ or _src/index.tsx_, by setting an optional option in the render method: `{ shadow: false }`
  
  It should look like this:
`ReactWebComponent.render(App, 'your-component', { shadow: false });`
